@startuml

node "Server Box" as ServerDocker {
    rectangle "Loc. Server" as ls
    rectangle "R.A.S.C. Server" as rs
    rectangle "Switch" as sw
    rectangle "Light controller" as lc
    rs --- sw : Ethernet
    rs --- lc : 3.3V
    ls --- sw : Ethernet
}

circle "Loc. Ant 1" as la1
circle "Loc. Ant 2" as la2
circle "Loc. Ant x" as lax

sw -- la1 : PoE
sw -- la2 : PoE
sw -- lax : PoE

circle "Light 1" as l1
circle "Light 2" as l2
circle "Light 3" as l3
circle "Light 4" as l4

lc -- l1 : 220V
lc -- l2 : 220V
lc -- l3 : 220V
lc -- l4 : 220V

rectangle "WiFi Router" as rt

node "Vehicle 1" as vh1 {
    rectangle "R.A.S.C. Client" as cl1
    rectangle "Monitor" as mn1
    rectangle "Speaker" as sp1
    cl1 -- mn1 : HDMI
    cl1 .. sp1 : BT
}

node "Vehicle x" as vh2 {
    rectangle "R.A.S.C. Client" as cl2
    rectangle "Monitor" as mn2
    rectangle "Speaker" as sp2
    cl2 -- mn2 : HDMI
    cl2 .. sp2 : BT
}
    rs ... rt : 802.11g
    rt ... cl1 : 802.11g
    rt ... cl2 : 802.11g

@enduml
